### ISSUE TITLE
Add subscribe_to for all events

### ISSUE THREAD

**Issue by Brandon2255p** [madedotcom/photon-pump#132]
After being able to read all events from #78 
It is now required that we are able to subscribe to all the events in order to retrieve new events

@bobthemighty Any insight you have on this would be appreciated. 
I will be tackling this soon because we will be needing this feature soon.

**Comment by bobthemighty** [comment]
Hi @Brandon2255p ,

I actually started looking at the $all functionality the other day. I'll be working on this over the next few days in my spare time. Subscriptions should already work, but I'll need to add support for catch-up subscriptions over $all.

I'm still wrestling with the API design, but I'm probably going to do the simplest thing and keep the existing iter/iter_all | get/get_all  methods, so all I need to do is add some documentation and fix a couple of wonky parameters.

What's your use-case for the subscription? Are you intending to use a persistent subscription, or a volatile subscription, and do you need catch-up?

**Comment by Brandon2255p** [comment]
That is great news then @bobthemighty ! 
I will test out the subscription if I get a moment today

We have not really made much use of subscriptions of any sort yet but from reading the difference between persistent and catch-up I think we would be going with a catch-up. I will try play around with the persistent subscription and see what that is about. I just hedged away from having the database track a client state but it is obviously normal so I will reconsider it

**Comment by Brandon2255p** [comment]
It seems that there is no way to create a persistent subscription to all events https://groups.google.com/forum/#!msg/event-store/9HzCJ08TZLI/0Se_ys3xoTEJ

**Comment by betaboon** [comment]
@bobthemighty any progress on this ?

**Comment by bobthemighty** [comment]
@betaboon and @Brandon2255p sorry for the delay on this. Other things took priority. I picked this up against yesterday. I've got the iter_all and get_all methods straightened up, and I've tested that I can create a volatile subscription to the all stream. I'll try and get a prototype `subscribe_all` method working today and open a PR for people to play with.

**Comment by betaboon** [comment]
@bobthemighty that is great news. your efforts are very much appreciated :)

**Comment by bobthemighty** [comment]
I've merged an alpha-quality implementation. It should _work_ but I need to do a massive refactor of the conversation types and figure out a better way of composing behaviours.

I'm not expecting any breaking changes to the interfaces, though. Once travis has finished, you should be able to install the pre-release version 0.8.0-alpha1 from pip 

https://github.com/madedotcom/photon-pump/releases/tag/v0.8.0-alpha1

**Comment by Brandon2255p** [comment]
Thanks so much! We have updated our library and will be pulling into this sprint

**Comment by betaboon** [comment]
Thank you very much :) just trying it out. already put some feedback in  #139

**Comment by betaboon** [comment]
argh. just noticed you need admin-privileges to access `$all` ...

**Comment by bobthemighty** [comment]
Yes unfortunately. That surprised me too, but it makes sense I suppose.

**Comment by betaboon** [comment]
that unfortunately somewhat destroys my usecase atm.
if only there would be an option to atleast create credentials for read-only on `$all`
