### ISSUE TITLE
Photonpump should send heartbeat requests to the server

### ISSUE THREAD

**Issue by bobthemighty** [madedotcom/photon-pump#33]
If we close the connection from underneath photonpump, eg. by terminating a VPN tunnel, then the client never notices any difference.

We should periodically (suggest every 60 secs) send a heartbeat request to the server. If we fail some consecutive number of requests, we should issue a reconnection request to the connection handler.

**Comment by bobthemighty** [comment]
If we implement the Connector, per #9 then we can hook this logic up in there. We'll set up some kind of dead man's switch, and write events for HeartbeatRequested, HeartbeatReceived, and HeartbeatTimeout into the queue.

**Comment by barrachri** [comment]
something like:

```python
error = 0
async def send_heartbeat(time=60, error=error):
    if error > 5:
         queue.put("HeartbeatError")
    try: 
        await i_am_alive(url)
       queue.put("HeartbeatReceived")
    except:
        error += 1
        queue.put("HeartbeatFailed")
    await asyncio.sleep(time)
```
