### ISSUE TITLE
Full iterator queues block heartbeats

### ISSUE THREAD

**Issue by bobthemighty** [madedotcom/photon-pump#49]

**Comment by barrachri** [comment]
So we fill the queue and when is full it blocks.

is this the problem?

**Comment by barrachri** [comment]
What about having a separate queue for `heartbeats` and separate between user related messages and internal messages?

**Comment by bobthemighty** [comment]
That would work, so the reader knows to put heartbeats on a separate queue, and we have a separate loop that reads them off replies/clears the timeout. It's just a bit fiddly to split it, and it's sort of annoying because the dispatcher is so central.

I guess that when we do #41 it'll seem less weird.

**Comment by barrachri** [comment]
I see.

I'll check how aioredis and aiokafka manage heartbeats, just to have some inspiration 👨‍🎨
