### ISSUE TITLE
Reading "$all" to read all events does not work.

### ISSUE THREAD

**Issue by Brandon2255p** [madedotcom/photon-pump#78]
I am trying to read all the events because we store every aggregate as a stream. Therefore we do not have the name of every stream.

The EventStore HTTP works by reading the stream $all. How do I do this? I see there is a TcpCommand ReadAllEventsBackward = 0xB8

**Comment by bobthemighty** [comment]
Hi @Brandon2255p - sorry for the total lack of response. I didn't see this until now. 

This would be a new feature request, but it's not particuarly hard to implement. I think we can probably manage it by creating new methods `iter_all` and `subscribe_to_all`. I'm tempted to just make the `stream` argument of `iter` and `subscribe_to` optional instead, but I'd need to think that through.

**Comment by Brandon2255p** [comment]
Thanks for the response. I would appreciate this feature being implemented. 

@bobthemighty I have forked this repo and implemented an iterAll method https://github.com/Brandon2255p/photon-pump/tree/all-events 

This was my first real attempt at python so its messy and does not have unit tests.. but it does the job for our current project

So when I have time I will attempt a PR into your repo

**Comment by bobthemighty** [comment]
Hi Brandon! This looks like great work!

Open the PR whenever you have a second, and I can help you with testing and any code issues, or you can hand the feature over as is.

 Well done :+1:

**Comment by Brandon2255p** [comment]
@bobthemighty Thanks 👍 I have put up a PR
